Add C# instance_statistics example
rticommunity/rticonnextdds-examples pull request #339
Opened 2021-02-26 19:49 UTC by alexcamposruiz

### Summary
Add C# directory for the instance_statistics example

### Details and comments
* This example uses the new C# API.
* I used better names for the IDL file, namespace, and type. I think the other examples should be updated.

2021-03-02 07:57 UTC, samuelraeburn approved these changes

2021-03-02 08:57 UTC, softwarejimenez approved these changes

2021-03-02 11:40 UTC, fgaranda requested changes

2021-03-02 11:40 UTC, fgaranda commented on examples/connext_dds/instance_statistics/cs/InstanceStatisticsExampleProgram.cs
> +* (c) Copyright, Real-Time Innovations, 2021.  All rights reserved.
These * are off by one space I think, same happens with other files.

2021-03-03 13:36 UTC, fgaranda approved these changes

2021-03-03 13:37 UTC, merged