C#: new examples and warning about deprecated API
rticommunity/rticonnextdds-examples pull request #352
Opened 2021-03-08 19:39 UTC by alexcamposruiz

### Summary
Update for the new C# API. Port the examples of multichannel, partitions. Add warning about deprecated API

### Details and comments
The multichannel and partitions examples have been ported to the new C# API. The old code has been deleted.

The rest of C# examples that use the old API now contain a warning in their README that points to the GSG.

2021-03-09 11:50 UTC, iblancasa requested changes

2021-03-09 11:50 UTC, iblancasa commented on examples/connext_dds/multichannel/cs/MarketDataSubscriber.cs
> +* (c) Copyright, Real-Time Innovations, 2012.  All rights reserved.
I think you need to fix here the copyright year

2021-03-09 11:50 UTC, iblancasa commented on examples/connext_dds/partitions/cs/PartitionsExampleSubscriber.cs
> +* (c) Copyright, Real-Time Innovations, 2012.  All rights reserved.
I think you need to fix here the copyright year

2021-03-09 15:50 UTC, iblancasa approved these changes

2021-03-10 10:12 UTC, fgaranda requested changes

2021-03-10 10:12 UTC, fgaranda commented on examples/connext_dds/asynchronous_publication/cs/README.md
> +[Getting Started Guide](https://community.rti.com/static/documentation/connext-dds/current/doc/manuals/connext_dds/getting_started/index.html).
You could use https://community.rti.com/static/documentation/connext-dds/6.1.0/doc/manuals/connext_dds_professional/getting_started_guide/csharp/before_csharp.html instead.

We can always do a bulk change when we bump the version, but the link to current is going to break.

2021-03-10 17:27 UTC, samuelraeburn approved these changes
Just one comment on possibly missing file, if it isn't missing all looks fine.

2021-03-10 18:55 UTC, alexcamposruiz commented on examples/connext_dds/multichannel/cs/MarketDataSubscriber.cs
> +/*
MarketDataProgram.cs is generated by rtiddsgen and doesn't need to change. I've updated the README because the codegen instructions were wrong.

2021-03-11 17:50 UTC, fgaranda approved these changes

2021-03-11 17:52 UTC, merged