[WIP] Feature/fix shapes processor
rticommunity/rticonnextdds-examples pull request #355
Opened 2021-03-09 16:17 UTC by iblancasa

### Summary
The example has a typo and it was not possible to build it. I did some fixes in the `CMakeLists.txt` too.

### Details and comments
Blocked by #354.

2021-03-15 12:44 UTC, lulivi approved these changes

2021-03-15 12:47 UTC, lulivi requested changes

2021-03-15 12:47 UTC, lulivi commented on examples/connext_dds/get_publishers/c++/Foo_publisher.cxx
> +    int count = 0;
There is a comment for this same line in https://github.com/rticommunity/rticonnextdds-examples/pull/356/files pr

2021-03-22 16:11 UTC, fgaranda approved these changes

2021-03-22 16:11 UTC, merged