Develop
rticommunity/rticonnextdds-examples pull request #364
Opened 2021-03-16 05:40 UTC by mcmanuea-rti

### Summary

### Details and comments

2021-03-16 14:43 UTC, alexcamposruiz requested changes
Looks good! Just a couple minor things.

2021-03-16 14:43 UTC, alexcamposruiz commented on examples/connext_dds/group_coherent_presentation/c++11/GroupCoherentExample_publisher.cxx
> +    // If you want to change the DataWriter's QoS programmatically rather
Delete this comment

2021-03-16 14:43 UTC, alexcamposruiz commented on examples/connext_dds/group_coherent_presentation/c++11/GroupCoherentExample_subscriber.cxx
> +                 for (auto& sample : samples) {
```suggestion
                 for (const auto& sample : samples) {
```

2021-03-16 20:31 UTC, alexcamposruiz approved these changes

2021-03-17 13:27 UTC, iblancasa requested changes

2021-03-17 13:27 UTC, iblancasa commented on examples/connext_dds/group_coherent_presentation/c++11/CMakeLists.txt
> +cmake_minimum_required(VERSION 3.7)
Required version is 3.11

2021-03-17 13:27 UTC, iblancasa commented on examples/connext_dds/group_coherent_presentation/c++11/CMakeLists.txt
> +# (c) 2018 Copyright, Real-Time Innovations, Inc. All rights reserved.
2021

2021-03-17 13:27 UTC, iblancasa commented on examples/connext_dds/group_coherent_presentation/c++11/CMakeLists.txt
> +	IDL "GroupCoherentExample"
Indentation

2021-03-17 13:27 UTC, iblancasa commented on examples/connext_dds/group_coherent_presentation/c++11/GroupCoherentExample.idl
> +module GroupCoherentExample
Missing copyright header

2021-03-17 13:27 UTC, iblancasa commented on examples/connext_dds/group_coherent_presentation/c++11/application.hpp
> +#endif  // APPLICATION_HPP
Add newline at the end of the file

2021-03-19 15:16 UTC, iblancasa approved these changes

2021-03-19 16:40 UTC, merged