Develop
rticommunity/rticonnextdds-examples pull request #367
Opened 2021-03-17 15:27 UTC by ManuelJNunez

:white_check_mark: I have updated the documentation accordingly.
:white_check_mark: I have read the CONTRIBUTING document.

### Summary

- Port flat_data_latency C++11 example to CMake.
- Update flat_data_latency C++11 README.md to the new template.

### Details and comments

Ref issue #261

2021-03-18 14:26 UTC, iblancasa requested changes
Good job!

2021-03-18 14:26 UTC, iblancasa commented on examples/connext_dds/flat_data_latency/c++11/CMakeLists.txt
> +    RTIConnextDDS::metp
Add one indentation level

2021-03-18 14:26 UTC, iblancasa commented on examples/connext_dds/flat_data_latency/c++11/CMakeLists.txt
> +    RTIConnextDDS::metp
Add one indentation level

2021-03-18 14:49 UTC, ManuelJNunez commented on examples/connext_dds/flat_data_latency/c++11/CMakeLists.txt
> +    RTIConnextDDS::metp
Done 👍🏻

2021-03-18 14:50 UTC, ManuelJNunez commented on examples/connext_dds/flat_data_latency/c++11/CMakeLists.txt
> +    RTIConnextDDS::metp
Done 👍🏻

2021-03-18 15:15 UTC, lulivi approved these changes

2021-03-22 09:05 UTC, fgaranda approved these changes

2021-03-22 15:51 UTC, iblancasa approved these changes

2021-03-22 16:10 UTC, merged