Fix githook issue
rticommunity/rticonnextdds-examples pull request #381
Opened 2021-03-24 10:28 UTC by ManuelJNunez

:white_check_mark: I have updated the documentation accordingly.
:white_check_mark: I have read the CONTRIBUTING document.

### Summary

The commit added in this PR solves the issue with `resources/githooks/pre-commit`. Basically, there was an environment variable creating this issue (take a look [here](https://stackoverflow.com/questions/56023577/why-does-git-commands-fail-when-run-as-part-of-a-git-hook-in-a-subfolder)), so I used `os.unsetenv` to solve the issue.

### Details and comments

Ref issue #380

2021-03-24 13:03 UTC, iblancasa requested changes

2021-03-24 13:03 UTC, iblancasa commented on resources/githooks/pre-commit
> +    main()
Add the removed final newline to the file

2021-03-24 13:03 UTC, lulivi requested changes

2021-03-24 13:03 UTC, lulivi commented on resources/githooks/pre-commit
> +    os.system(str(formater) + " -a")
I think this will be cleaner
```suggestion
    os.system(f"{str(formater)} -a")
```

2021-03-24 13:03 UTC, lulivi commented on resources/githooks/pre-commit
> +    os.unsetenv("GIT_DIR")
Why do you unset that variable?

2021-03-24 13:04 UTC, lulivi commented on resources/githooks/pre-commit
> +    os.unsetenv("GIT_DIR")
Oh just saw the description, my bad

2021-03-24 23:50 UTC, lulivi approved these changes

2021-03-25 16:31 UTC, iblancasa approved these changes

2021-03-25 18:39 UTC, merged