Move TravisCI Build to GH Actions
rticommunity/rticonnextdds-examples pull request #394
Opened 2021-03-29 10:03 UTC by ManuelJNunez

:white_check_mark: I have updated the documentation accordingly.
:white_check_mark: I have read the CONTRIBUTING document.

### Summary

I created a GH Actions workflow that builds all the examples and executes the static analysis. Also, I removed the execution of the linters from this workflow because there are others that execute them.

### Details and comments

close #349

2021-03-29 10:04 UTC, ManuelJNunez commented
It's necessary to configure the secrets in this repository to make the workflow work properly.

2021-03-29 13:42 UTC, iblancasa commented
@fgaranda and @lulivi can you help @ManuelJNunez with this?

2021-03-29 20:28 UTC, fgaranda approved these changes

2021-03-30 15:06 UTC, lulivi commented
It seems to be working fine, right? no errors or warning at all. Pretty cool!

Should we fail the build if any of the required environment variables are not defined? Instead of Skipping it?

2021-03-30 15:32 UTC, ManuelJNunez commented
Actually there is a problem, but it will be fixed soon. Take a look at #397

2021-03-31 09:51 UTC, ManuelJNunez commented
The other workflow will not run until this PR is merged.

2021-03-31 09:51 UTC, ManuelJNunez commented
close #397

2021-04-05 07:51 UTC, lulivi requested changes

2021-04-05 07:51 UTC, lulivi commented on .github/workflows/build.yml
> +        if: ${{ github.event_name == 'workflow_run' }}
```suggestion
      - name: Unzip artifact
        if: ${{ github.event_name == 'workflow_run' }}
        run: unzip pr.zip
```
To follow a convention

2021-04-05 07:51 UTC, lulivi commented on .github/workflows/build.yml
> +      - uses: actions/checkout@v2
One of these two `- uses` is not correct. Maybe the first one?

2021-04-05 08:22 UTC, lulivi approved these changes

2021-04-07 08:56 UTC, lulivi commented
I'm not sure why the build is not triggering... maybe we need to merge it in order for the build to trigger? The thing is that the artifact uploading is trigerring.

2021-04-07 09:11 UTC, ManuelJNunez commented
@lulivi You're right, the other workflow is executed in the context of this repository (cannot be executed on forks), so it has to be merged.

2021-04-07 09:53 UTC, lulivi commented
But the purpose is for it to execute on pull requests, too, right?

2021-04-07 09:58 UTC, ManuelJNunez commented
@lulivi It will be executed in the next Pull Request if this one is merged, it cannot be executed in this fork.

2021-04-07 09:59 UTC, angelrti requested changes

2021-04-07 09:59 UTC, angelrti commented on .github/workflows/build.yml
> +name: build
this is a test message

2021-04-07 10:22 UTC, merged