Fix for #408
rticommunity/rticonnextdds-examples pull request #409
Opened 2021-04-13 22:20 UTC by pralhadsapre

2021-04-13 22:21 UTC, pralhadsapre commented
I fixed the compilation issues found during install testing. The problem was related to setting the C++ standard in CMake.

2021-04-14 03:58 UTC, juanlu-rti approved these changes

2021-04-14 07:17 UTC, lulivi requested changes
Just that little change!

2021-04-14 07:17 UTC, lulivi commented on examples/routing_service/routing_service_struct_array_transf/cpp/CMakeLists.txt
> +)
```suggestion
)

```
Please, add an endline!

2021-04-14 23:52 UTC, pralhadsapre commented on examples/routing_service/routing_service_struct_array_transf/cpp/CMakeLists.txt
> +)
Done.

2021-04-14 23:58 UTC, pralhadsapre commented
@lulivi I think there is some issue with the linter. I am seeing this message - ``Configuration file(s) do(es) not support C++: /home/runner/work/rticonnextdds-examples/rticonnextdds-examples/.clang-format``.

2021-04-15 08:42 UTC, lulivi commented
We are fixing it right now!

2021-04-15 10:35 UTC, lulivi approved these changes

2021-04-15 10:36 UTC, lulivi commented
@pralhadsapre can you merge develop into your branch to see if the linter runs with the new config?

2021-04-16 07:21 UTC, lulivi commented
Tested locally and works as expected:

![image](https://user-images.githubusercontent.com/10894592/114987012-fc4a2c80-9e94-11eb-82be-1327263f3f33.png)

2021-04-16 09:16 UTC, angelrti approved these changes

2021-04-16 09:16 UTC, angelrti commented on examples/routing_service/routing_service_struct_array_transf/cpp/CMakeLists.txt
> +# (c) 2021 Copyright, Real-Time Innovations, Inc.  All rights reserved.
It's not needed to update the copyright year, so, don't worry too much about these changes

2021-04-16 13:36 UTC, merged