Improve pull request template
rticommunity/rticonnextdds-examples pull request #413
Opened 2021-04-14 09:52 UTC by ManuelJNunez

### Summary

I updated the `PULL_REQUEST_TEMPLATE.md` to remind everyone to update the top-level CMake when a new `C/C++` example is added.

### Details and comments

close #411

2021-04-14 09:54 UTC, lulivi requested changes

2021-04-14 09:54 UTC, lulivi commented on .github/PULL_REQUEST_TEMPLATE.md
> +-   [ ] I added a new C/C++ example and updated `resources/connext_dds/CMakeList.txt`.
```suggestion
-   [ ] I added a new C/C++ example and updated `examples/connext_dds/CMakeList.txt`.
```

2021-04-16 09:19 UTC, angelrti approved these changes

2021-04-20 14:15 UTC, angelrti requested changes

2021-04-20 14:15 UTC, angelrti commented on .github/PULL_REQUEST_TEMPLATE.md
> +<!-- Uncomment bellow if you added a C/C++ example and updated examples/connext_dds/CMakeList.txt -->
```suggestion
<!-- Uncomment the bellow bullet if you have added a C/C++ example -->
```

2021-04-20 14:15 UTC, angelrti commented on .github/PULL_REQUEST_TEMPLATE.md
> +-   [ ] I added a new C/C++ example and updated `examples/connext_dds/CMakeList.txt`.
```suggestion
-   [ ] I have added a new C/C++ example and updated `examples/connext_dds/CMakeList.txt`.
```

2021-04-26 08:41 UTC, lulivi submitted a review, later dismissed

2021-05-18 11:56 UTC, lulivi commented
Maybe here we could add the new check once the Grade execution is enabled

2021-11-24 16:03 UTC, lulivi submitted a review, later dismissed

2021-11-30 09:10 UTC, fgaranda requested changes

2021-11-30 09:10 UTC, fgaranda commented on .github/PULL_REQUEST_TEMPLATE.md
> +-   [ ] I added a new C/C++ example and updated `examples/connext_dds/CMakeList.txt`.
```suggestion
-   [ ] I have added a new C/C++ example and updated `examples/connext_dds/CMakeList.txt` accordingly.
```

2021-11-30 09:10 UTC, fgaranda commented on .github/PULL_REQUEST_TEMPLATE.md
> +-   [ ] I added a new Java example and updated `examples/connext_dds/settings.gradle`.
```suggestion
-   [ ] I have added a new Java example and updated `examples/connext_dds/settings.gradle` accordingly.
```

2021-11-30 10:52 UTC, fgaranda approved these changes

2021-11-30 12:20 UTC, angelrti approved these changes

2021-11-30 12:22 UTC, merged