Divide the linux_static_analysis script
rticommunity/rticonnextdds-examples pull request #443
Opened 2021-05-19 11:17 UTC by ManuelJNunez

### Summary

The functionality of the linux_static_analysis script was divided into two scripts. This was done because, in the future Jenkins pipeline, Valgrind will be executed in parallel with the static analysis.

### Details and comments

close #442 

### Checks

-   [x] I have updated the documentation accordingly.
-   [x] I have read the [CONTRIBUTING](https://github.com/rticommunity/rticonnextdds-examples/blob/develop/CONTRIBUTING.md) document.

2021-05-20 07:34 UTC, lulivi commented on resources/ci_cd/linux_static_analysis.py
> +"""Build all the examples.
```suggestion
"""Run static analysis over all the built examples.```

2021-05-24 07:35 UTC, lulivi approved these changes

2021-05-24 11:07 UTC, lulivi requested changes

2021-05-24 11:07 UTC, lulivi commented on resources/ci_cd/linux_static_analysis.py
> +    )
```suggestion
    try:
        rti_installation_path = Path(
            os.getenv("RTI_INSTALLATION_PATH") or Path.home()
         ).resolve(strict=True)
    except FileNotFoundError:
        sys.exit("The RTI_INSTALLATION_PATH does not exist.")
```

2021-05-24 11:07 UTC, lulivi commented on resources/ci_cd/linux_static_analysis.py
> +        sys.exit("The RTI_INSTALLATION_PATH does not exist.")
```suggestion
```

2021-05-24 11:07 UTC, lulivi commented on resources/ci_cd/linux_static_analysis.py
> +    if len(found_rti_connext_dds) == 0:
```suggestion
    if found_rti_connext_dds:
```

2021-05-24 14:04 UTC, lulivi approved these changes

2021-05-24 15:13 UTC, fgaranda approved these changes

2021-05-24 15:55 UTC, lulivi approved these changes

2021-05-24 15:56 UTC, merged