Required Subscription example
rticommunity/rticonnextdds-examples pull request #450
Opened 2021-06-30 16:32 UTC by IreneAlejoTeissiere

### Summary

Francis and I have created an example about the Required Subscription feature

### Details and comments

It is created only for C++. The important part is the QOS configuration that is in the USER_QOS_PROFILE.xml,
So we consider that is not significant to add another language.

### Checks

-   [x] I have updated the documentation accordingly.
-   [x] I have read the [CONTRIBUTING](https://github.com/rticommunity/rticonnextdds-examples/blob/develop/CONTRIBUTING.md) document.

2021-11-11 16:56 UTC, fgaranda requested changes

2021-11-11 17:17 UTC, IreneAlejoTeissiere commented on examples/connext_dds/required_subscription/c++/RequiredSubscriptions_publisher.cxx
> +        std::cerr << "write error " << retcode << std::endl;
yes, and return an error status. Done

2021-11-11 17:22 UTC, fgaranda approved these changes

2021-11-12 06:09 UTC, juanlu-rti approved these changes

2021-11-17 10:08 UTC, merged