Upgrade Connext DDS version in master to 6.1.1
rticommunity/rticonnextdds-examples pull request #493
Opened 2022-05-04 16:14 UTC by fgaranda

### Summary
This PR upgrades the version master targets to Connext DDS 6.1.1.

### Details and comments

As part of this PR, we upgrade schema files, build scripts, and other infrastructure in the master branch to use Connext DDS 6.1.1.

### Checks

-   [x] I have updated the documentation accordingly.
-   [x] I have read the [CONTRIBUTING](https://github.com/rticommunity/rticonnextdds-examples/blob/develop/CONTRIBUTING.md) document.

2022-05-04 17:01 UTC, alexcamposruiz requested changes

2022-05-04 17:01 UTC, alexcamposruiz commented on examples/connext_dds/dynamic_data_using_publisher_subscriber/cs/Shapes.csproj
> -    <PackageReference Include="Rti.ConnextDds.Extra" Version="6.1.0" />
The search/replace is wrong. It removed .Extra in many .csprojs.

2022-05-05 08:11 UTC, ManuelJNunez commented
We are currently upgrading the Connext Version of the bundle used for CI. Once it is ready we can restart the CI workflow.

2022-05-05 08:12 UTC, ManuelJNunez commented
Also, I'm going to temporarily deactivate the linting for .NET.

2022-05-10 15:01 UTC, alexcamposruiz approved these changes

2022-05-10 19:26 UTC, lulivi commented
Waiting for the build to end.

2022-05-10 20:27 UTC, ManuelJNunez approved these changes

2022-05-10 22:09 UTC, merged