Added a new LBED and XML-Based Application Creation example
rticommunity/rticonnextdds-examples pull request #536
Opened 2022-09-27 14:35 UTC by alvarillo89

### Summary

Add a new example that shows how to configure LBED along with XML-Based Application Creation.

### Details and comments

I just added the C++11 example. The example uses the ShapeType form RTI Shapes Demo, but I removed the ShapeTypeExtended. Is that ok?
I also used both style-checking tools: clang-format and markdownlint.

### Checks

-   [X] I have updated the documentation accordingly.
-   [X] I have read the [CONTRIBUTING](https://github.com/rticommunity/rticonnextdds-examples/blob/develop/CONTRIBUTING.md) document.

-   [ ] I have added a new C/C++ example and updated `examples/connext_dds/CMakeList.txt` accordingly.

2022-09-27 15:13 UTC, alexcamposruiz commented on examples/connext_dds/lbediscovery/c++11/ShapeType_publisher.cxx
> +    dds::pub::DataWriter<ShapeType> blue_writer =
```suggestion
    auto blue_writer =
```

2022-09-27 15:13 UTC, alexcamposruiz commented on examples/connext_dds/lbediscovery/c++11/ShapeType_publisher.cxx
> +    dds::pub::DataWriter<ShapeType> red_writer =
```suggestion
    auto red_writer =
```

2022-09-27 15:16 UTC, alexcamposruiz commented on examples/connext_dds/lbediscovery/c++11/ShapeType_subscriber.cxx
> +        readers.push_back(rti::sub::find_datareader_by_name<
Get the reader first, check for `dds::core::null` (and throw runtime_error), then add it.

2022-09-27 15:26 UTC, alexcamposruiz commented on examples/connext_dds/lbediscovery/c++11/ShapeType_subscriber.cxx
> +    std::vector<dds::sub::DataReader<ShapeType>> readers;
Use a constant instead of `4`.

2022-09-27 15:26 UTC, alexcamposruiz commented on examples/connext_dds/lbediscovery/c++11/ShapeType_subscriber.cxx
> +    while (!application::shutdown_requested && samples_read[0] < sample_count
```
auto below_sample_count = [sample_count](unsigned int count) { return count < sample_count; }
while (!application::shutdown_requested && std::all_of(sample_read.begin(), samples_read.end(), below_sample_count))
```

2022-09-30 19:54 UTC, rkorte commented on examples/connext_dds/lbediscovery/README.md
> +If your application uses XML-Based Application Creation, you do not have to
If your application uses XML-Based Application Creation, however, you do not have to

2022-09-30 19:54 UTC, rkorte commented on examples/connext_dds/lbediscovery/README.md
> +with `color=RED`. The other two, filter samples with `color=BLUE`.
The other two filter samples with `color=BLUE`.

2022-09-30 19:54 UTC, rkorte commented on examples/connext_dds/lbediscovery/c++11/README.md
> +Alternatively, you can use directly the generated infrastructure (e.g.,
Alternatively, you can directly use the generated infrastructure (e.g.,

2022-09-30 19:54 UTC, rkorte commented on examples/connext_dds/lbediscovery/c++11/README.md
> +installation folder. For example:
Change all instances of Connext DDS in this paragraph to Connext. (We are phasing out the "DDS" in "Connext DDS.")

2022-09-30 20:36 UTC, mcmanuea-rti requested changes

2022-09-30 20:36 UTC, mcmanuea-rti commented on examples/connext_dds/lbediscovery/c++11/ShapeType.idl
> +};//@Extensibility EXTENSIBLE_EXTENSIBILITY
use the new annotation style:
```
@appendable
struct ShapeType
{
    @key
    string<128> color;
    long x;
    long y;
    long shapesize;
};
```

2022-10-04 19:55 UTC, mcmanuea-rti submitted a review, later dismissed

2022-10-05 16:43 UTC, rkorte submitted a review, later dismissed

2022-10-07 15:46 UTC, alexcamposruiz requested changes

2022-10-07 15:46 UTC, alexcamposruiz commented on examples/connext_dds/lbediscovery_xml_app_creation/c++11/ShapeType_subscriber.cxx
> +    const unsigned int reader_number = 4;
```suggestion
    const unsigned int reader_count = 4;
```

2022-10-07 15:46 UTC, alexcamposruiz commented on examples/connext_dds/lbediscovery_xml_app_creation/c++11/ShapeType_subscriber.cxx
> +        reader = rti::sub::find_datareader_by_name<
declare the variable `reader` here as `auto` instead of initializing it to `null` above.

2022-10-07 15:46 UTC, alexcamposruiz commented on examples/connext_dds/lbediscovery_xml_app_creation/c++11/ShapeType_subscriber.cxx
> +        for (int i = 0; i < reader_number; i++) {
```
for (auto& waitset : waisets) {
    waitset.dispatch(...)
}
```

2022-10-10 15:07 UTC, alexcamposruiz requested changes

2022-10-10 15:07 UTC, alexcamposruiz commented on examples/connext_dds/lbediscovery_xml_app_creation/c++11/ShapeType_subscriber.cxx
> +        const std::string reader_name)
```suggestion
        const std::string& reader_name)
```

2022-10-17 15:49 UTC, alexcamposruiz submitted a review, later dismissed

2022-10-18 17:41 UTC, lulivi commented on examples/connext_dds/lbediscovery_xml_app_creation/c++11/README.md
> +1. The `<domain_id>`. Both applications must use the same domain ID in order to
```suggestion
1.  The `<domain_id>`. Both applications must use the same domain ID in order to
```
Can you add a space here and before all other numbered and unnumbered lists? (63, 66. 77, 82, 87, 126 29 and 131)

2022-10-18 17:47 UTC, lulivi requested changes
https://github.com/rticommunity/rticonnextdds-examples/pull/536#discussion_r998534151

2022-10-19 09:55 UTC, lulivi approved these changes

2022-10-19 15:20 UTC, merged