IRONSIDE-422
rticommunity/rticonnextdds-examples pull request #592
Opened 2023-02-17 11:59 UTC by juanlu-rti

Adding cloning instructions to the main README file in the examples repository

### Summary

### Details and comments

### Checks

-   [ ] I have updated the documentation accordingly.
-   [ ] I have read the [CONTRIBUTING](https://github.com/rticommunity/rticonnextdds-examples/blob/develop/CONTRIBUTING.md) document.

2023-02-17 14:35 UTC, fgaranda requested changes

2023-02-17 14:35 UTC, fgaranda commented on README.md
> +git clone --recurse-submodule https://github.com/rticommunity/rticonnextdds-gateway-opcua.git
```suggestion
git clone --recurse-submodule https://github.com/rticommunity/rticonnextdds-examples.git
```

2023-02-18 01:33 UTC, rkorte submitted a review, later dismissed

2023-02-22 11:04 UTC, lulivi approved these changes

2023-02-23 05:45 UTC, rkorte approved these changes

2023-02-23 11:25 UTC, fgaranda approved these changes

2023-02-23 12:38 UTC, merged