Add Modern C++ DL example
rticommunity/rticonnextdds-examples pull request #632
Opened 2023-10-24 20:37 UTC by luisrg-rti

This example requires changes to the `cmake-utils` sub-repository before it can be compiled

2023-10-26 09:02 UTC, lulivi commented
Hey @luisrg-rti can you move the source code to the main directory similarly to all the other examples? https://github.com/rticommunity/rticonnextdds-examples/tree/develop/examples/connext_dds/asyncwaitset/c%2B%2B11 same with the header file.

2023-10-26 09:03 UTC, lulivi commented
Also take a look to the linting https://github.com/rticommunity/rticonnextdds-examples/actions/runs/6633405661/job/18021065371?pr=632 and formatting https://github.com/rticommunity/rticonnextdds-examples/actions/runs/6633405665/job/18021065354?pr=632.

2023-10-26 17:32 UTC, lulivi commented on examples/distributed_logger/c++11/CMakeLists.txt
> +include(ConnextDdsAddExample)
```suggestion
```

This is not used here

2023-10-26 17:33 UTC, lulivi commented on examples/distributed_logger/c++11/CMakeLists.txt
> +    "${CMAKE_CURRENT_SOURCE_DIR}/../../../resources/cmake/Modules"
Remember to add an extra `../` when this is moved to `examples/connext_dds`

2023-10-26 17:50 UTC, alexcamposruiz commented
Make the example consistent with the rest:

1. Move to connext_dds
2. Create a top-level README with language-independent description of the example, and mention that for other languages the examples are shipped (see the basic_security example for ex)
3. Move all sources to c++11 (remove src and include dirs)
4. Make the c++11/README.md focus on how to run the c++11 example only.

2023-10-26 18:06 UTC, luisrg-rti commented
> Make the example consistent with the rest:
> 
>     1. Move to connext_dds
> 
>     2. Create a top-level README with language-independent description of the example, and mention that for other languages the examples are shipped (see the basic_security example for ex)
> 
>     3. Move all sources to c++11 (remove src and include dirs)
> 
>     4. Make the c++11/README.md focus on how to run the c++11 example only.

I'll make these changes. I think I may have followed the structure of the other DL examples in `connextdds/examples.1.0` by mistake.

2023-11-03 13:08 UTC, lulivi commented
Hi @luisrg-rti can you add your `distributed_logger` directory to here? https://github.com/rticommunity/rticonnextdds-examples/blob/master/examples/connext_dds/CMakeLists.txt#L108

2023-11-03 13:18 UTC, lulivi commented
Once the [cmake-utils PR](https://github.com/rticommunity/rticonnextdds-cmake-utils/pull/109) is merged, we will launch a final build (after the `examples/connext_dds/CMakeLists.txt` change is done) to check everything working as expected

2023-11-15 18:20 UTC, alexcamposruiz requested changes

2023-11-15 18:20 UTC, alexcamposruiz commented on examples/connext_dds/distributed_logger/README.md
> +The log messages can then be visualized using RTI Tools such as RTI Spy
Can you add a shell ```-block showing how to run spy and the expected output?

2023-11-17 16:22 UTC, alexcamposruiz approved these changes

2023-11-20 10:02 UTC, merged

2023-11-20 10:03 UTC, lulivi commented
Seems to be working fine:
```
2023-11-17T07:29:55.8992829Z [ 25%] Building CXX object connext_dds/distributed_logger/c++11/CMakeFiles/DistLoggerExample.dir/DistLoggerExample.cxx.o 
2023-11-17T07:29:57.0808939Z [ 25%] Linking CXX executable DistLoggerExample                        
2023-11-17T07:29:57.1604108Z [ 25%] Built target DistLoggerExample
```