EVALG-75: Add Application Design tutorial
rticommunity/rticonnextdds-examples pull request #693
Opened 2024-07-03 13:45 UTC by Alxe

### Summary

Add new tutorial for Application Design

### Details and comments

### Checks

-   [ ] I have updated the documentation accordingly.
-   [ ] I have read the [CONTRIBUTING](https://github.com/rticommunity/rticonnextdds-examples/blob/develop/CONTRIBUTING.md) document.

2024-07-08 10:41 UTC, Alxe commented
@alexcamposruiz Please, review this PR.

2024-07-11 18:22 UTC, alexcamposruiz requested changes

2024-07-11 18:22 UTC, alexcamposruiz commented on tutorials/application_design/py/README.md
> +$ python3.8 -m publisher
```suggestion
$ python publisher.py
```

2024-07-11 18:22 UTC, alexcamposruiz commented on tutorials/application_design/py/README.md
> +The publisher can be run as a file or module. The expected output contains a
For consistency with the rest of this repo, provide the instructions to run as a file only.

2024-07-11 18:22 UTC, alexcamposruiz commented on tutorials/application_design/py/VehicleModeling.py
> +# WARNING: THIS FILE IS AUTO-GENERATED. DO NOT MODIFY.
remove warning; replace with (c)

2024-07-11 18:51 UTC, alexcamposruiz approved these changes

2024-07-11 18:52 UTC, merged