CORE-14969: Remove asynchronous publishing from examples in which it is no longer needed
rticommunity/rticonnextdds-examples pull request #700
Opened 2024-08-09 11:47 UTC by alvarillo89

### Summary

Now that asynchronous publishing is no longer a requirement for sending reliable fragmented data, I reviewed all our GitHub examples and removed the asynchronous publish mode from all the places in which it is no longer necessary.

### Details and comments

Mostly, update documentation and `USER_QOS_PROFILES.xml` files.

### Checks

-   [X] I have updated the documentation accordingly.
-   [X] I have read the [CONTRIBUTING](https://github.com/rticommunity/rticonnextdds-examples/blob/develop/CONTRIBUTING.md) document.

2024-08-12 23:51 UTC, rkorte requested changes

2024-08-12 23:51 UTC, rkorte commented on examples/connext_dds/flat_data_latency/c++11/README.md
> +protocol, the history, and how dynamic memory allocations are handled. In the
```suggestion
protocol, the history, and the handling of dynamic memory allocations. In the
```

2024-08-12 23:51 UTC, rkorte commented on examples/connext_dds/flat_data_latency/c++11/README.md
> +*DataRepresentation QoS* is set to *Extended CDR version 2* at both the
```suggestion
*DataRepresentation QoS* is set to *Extended CDR version 2* on both the
```

2024-08-12 23:51 UTC, rkorte commented on examples/connext_dds/flat_data_latency/c++11/README.md
> +DataWriter and the DataReader as FlatData language binding is only supported
```suggestion
DataWriter and the DataReader since FlatData language binding is only supported
```

2024-08-19 10:24 UTC, alvarillo89 commented
I tested all the modified examples except the `real_time_wan_transport`, which requires a specific network infrastructure, locally with the last version of _RTI Connext_. **Everything worked as expected.**

2024-08-19 15:55 UTC, rkorte approved these changes

2024-08-20 13:51 UTC, samuelraeburn approved these changes

2024-08-22 10:19 UTC, merged